### ISSUE TITLE
[Unity 2018.3.6f1] Unity freezes when adjusting Fractal Power value in Mandelbulb scene

### ISSUE THREAD

**Issue by RyanDunagan7899** [SebLague/Ray-Marching#1]
This is a wonderful demonstration of what Unity is capable of. Thank you for sharing it.

When adjusting the Fractal Power value in the Mandelbulb scene, Unity will freeze. If adjusted in the editor out of play mode, in the editor in play mode, or in a build of the scene, the editor/build will freeze.

I tried only incrementing the Fractal Power on a button hold, and it would run fine until I pressed the button. The value would increment slightly, and the bulb would visually adjust, then the editor/build would freeze.

Also, the script associations in the scene (1 on Main Camera, and 2 on its child object Camera) were broken.

**Comment by RyanDunagan7899** [comment]
I've just discovered that rotating the main camera in the Mendelbulb scene will cause a similar freeze of the editor.

**Comment by sliterok** [comment]
I guess that's something to do with the amount of computation required to render such scene. I was monitoring my gpu usage while moving camera in the Mendelbulb scene and at the moment of freeze gpu usage rocketed to 100%

**Comment by RyanDunagan7899** [comment]
@sliterok The same GPU usage spike occurs on my 1080Ti, however I did some further testing and found out that if I disable the FractalMaster script on the camera, move the camera coordinates away from where it is located in the scene and re-enable it, the crash in editor also occurs.

![GPU Spike](https://user-images.githubusercontent.com/35862069/55601713-69ac1a00-571f-11e9-8387-1e6853cab124.png)

Oddly enough, Unity will still exit just fine using the X in the top left to close the application without need for a force close via task manager.

I've been looking at the Fractal Compute Shader code to see if there was anything that stood out as something that could be cleaned up, but I've only just begun learning shader programming, so I don't think I'm the man for the job.

**Comment by SebLague** [comment]
I've added a max march step count to the mandelbulb shader, which will hopefully resolve this. Please let me know if it's still crashing and I'll reopen the issue.

**Comment by nachoskywalker** [comment]
Hello Seb and others. I am having a similar problem. I have a compute shader under unity which is helping me to calculate some data to acelerate marching shadows. In the moment I increase the internal loops a little bit the compute is not slower. It just gets frozen. Do you know if there is a limit in the internal loops in a shader or maybe a limit in time or something. Its really hard to debug the problem. Thanks a lot!! :)
